name: Test Build Scripts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build.sh
      run: ./build.sh

  test-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install MinGW
      run: choco install mingw --version=8.1.0
      shell: cmd

    - name: Add MinGW to PATH
      run: echo "::add-path::C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
      shell: powershell

    - name: Run build.ps1
      run: .\build.ps1
      shell: powershell
        