name: Build C++ Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment
      run: sudo apt-get install g++

    - name: Compile C++ files
      run: g++ /src/*.cpp -o /bin/main

    - name: Display bin directory contents
      run: ls -la ./bin
